### ISSUE TITLE
improvement: add default-container annotation to splunk-operator

### ISSUE THREAD

**Issue by mdaniel** [splunk/splunk-operator#765] opened 2022-04-28 22:06 UTC
Per [the documentation](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container), if the Pod were annotated with `kubectl.kubernetes.io/default-container`, then `kubectl logs deploy/splunk-operator-controller-manager` would have a reasonable default

# What happens right now?

```console
$ kubectl -n splunk-operator logs deploy/splunk-operator-controller-manager
error: a container name must be specified for pod splunk-operator-controller-manager-6465874c68-lxn95, choose one of: [kube-rbac-proxy manager]
```

# What should happen?

```console
$ kubectl -n splunk-operator patch -p '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container": "manager"}}}}}' deploy/splunk-operator-controller-manager
$ kubectl -n splunk-operator rollout status deploy/splunk-operator-controller-manager
deployment "splunk-operator-controller-manager" successfully rolled out
$ kubectl -n splunk-operator logs deploy/splunk-operator-controller-manager
2022-04-28T22:04:25.519Z        INFO    setup   Manager will be watching namespace      {"namespace": ""}
...
```

**Comment by akondur** [comment] 2022-05-02 20:11
Hi @mdaniel , when I tried the following commands:

```
kubectl -n splunk-operator patch -p '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container": "manager"}}}}}' deploy/splunk-operator-controller-manager

kubectl -n splunk-operator rollout status deploy/splunk-operator-controller-manager
```

I still see the following error:
```
$ kubectl -n splunk-operator logs deploy/splunk-operator-controller-manager                                                                                                                                                                                                                                                   [252/9274]
error: a container name must be specified for pod splunk-operator-controller-manager-66d5456c6b-n7bmn, choose one of: [kube-rbac-proxy manager]
```

However, if I patch the following annotation:
```
kubectl -n splunk-operator patch -p '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-logs-container": "manager"}}}}}' deploy/splunk-operator-controller-manager
```

I am able to:

**Display logs from deployment without mentioning the container:**

```
$ kubectl -n splunk-operator logs deploy/splunk-operator-controller-manager
2022-05-02T19:22:26.110Z        INFO    setup   Manager will be watching namespace      {"namespace": ""}
2022-05-02T19:22:27.115Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2022-05-02T19:22:27.116Z        INFO    setup   starting manager
I0502 19:22:27.117369       1 leaderelection.go:248] attempting to acquire leader lease splunk-operator/270bec8c.splunk.com...
2022-05-02T19:22:27.117Z        INFO    starting metrics server {"path": "/metrics"}
```

**Display logs from the pod without mentioning the container:**
```
$ kubectl logs splunk-operator-controller-manager-5b4d8bcd7d-kb2fj
2022-05-02T19:22:26.110Z        INFO    setup   Manager will be watching namespace      {"namespace": ""}
2022-05-02T19:22:27.115Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2022-05-02T19:22:27.116Z        INFO    setup   starting manager
I0502 19:22:27.117369       1 leaderelection.go:248] attempting to acquire leader lease splunk-operator/270bec8c.splunk.com...
2022-05-02T19:22:27.117Z        INFO    starting metrics server {"path": "/metrics"}
```

I am currently using K8s version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Please let me know if this works(I've raised a [PR](https://github.com/splunk/splunk-operator/pull/777)). Also if you could provide the K8s version used on your end to see if there have been enhancements to the annotation.

**Comment by mdaniel** [comment] 2022-05-02 22:19
I could have sworn [api - 1 was the only supported gap](https://kubernetes.io/releases/version-skew-policy/), so I could not run a 1.18 `kubectl` but yes, I'm a good k8s-er and keep my tooling up to date via Homebrew:
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-20T23:37:42Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-14c7a48", GitCommit:"717bfb2b8ceb809a42a6c0baabde59fae28637ef", GitTreeState:"clean", BuildDate:"2022-04-01T03:17:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
and my kubectl does whine just like their docs say it should:
> WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

That said, annotations are free, so if yours works with `"kubectl.kubernetes.io/default-logs-container"`, toss that one in, too, and then just watch out for what the old version of `kubectl` wants in order to know the default container for `kubectl exec`

**Comment by akondur** [comment] 2022-05-03 04:10
Hi @mdaniel , I have added both the annotations in the PR. The [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/2227-kubectl-default-container/README.md) here adds support for the annotation `default-container` at a time where only `default-logs-container` was supported to extend the annotation to `kubectl exec` & a couple of other commands. In my research, unfortunately for older versions of kubectl there is no support for default container for exec commands.

**Comment by akondur** [comment] 2022-05-04 18:50
Closing as the issue is fixed via the [PR](https://github.com/splunk/splunk-operator/pull/777).

**Closed by akondur** 2022-05-04 18:50 UTC
