### ISSUE TITLE
Cluster master secret ref deleted when CM CRD is deleted

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#182] opened 2020-11-26 01:24 UTC
I created a secret for use by the smartstore configuration secretRef when I delete a CM instance the secret is incorrectly delete
  smartstore:
    volumes:
      - name: primary
        path: spl-11111-splunk-s3/gdi
        endpoint: https://s3-us-east-2.amazonaws.com
        secretRef: spl-1111-splunk-s3

**Comment by akondur** [comment] 2020-11-30 23:52
Hi @rfaircloth-splunk , could you share the following details regarding the issue you are seeing:

1. Configuration yaml files of the ClusterMaster, IndexerCluster
2. Kubernetes version being used
3. Operator release being used
4. Steps followed to reproduce the issue
5. Operator logs at the time when the issue occurred(if possible)

**Note**: I tried creating a multi-site indexer cluster with SmartStore locally and upon deletion of the ClusterMaster CR the smartstore **secretRef** still remains undeleted on the cluster.

**Comment by akondur** [comment] 2022-04-01 19:29
Hi @rfaircloth-splunk , the issue is fixed in the latest release as we remove the secret owner references(for the smartstore secrets) via finalizers.

**Closed by akondur** 2022-04-01 19:29 UTC
