### ISSUE TITLE
Only first pod of StatefulSet updated on modification of SearchHeadCluster or IndexerCluster (e.g. image, resources)

### ISSUE THREAD

**Issue by romain-bellanger** [splunk/splunk-operator#213] opened 2020-12-19 20:36 UTC
Hello,

This is an impact of #193: on change of SearchHeadCluster or IndexerCluster custom resource properties such as image or resource quotas, only the first pod of the associated StatefulSet is updated. The purpose of this PR was precisely to update the ```controller-revision-hash``` label of all the pods to prevent their restart.

We are currently working on the upgrade of clusters in Splunk 8.0.6 deployed with the operator alpha version 0.1.0, to Splunk 8.1.0.1 with the operator beta version 0.2.1. This breaks a lot of automation in the upgrade process. When changing the docker image, pods were previously restarted sequentially with a proper offline (for indexers), which was matching the requirements for a clean upgrade (with just a couple of additional API calls to initialize / finalize the process). With this change only the first pod is restarted automatically. The upgrade of the remaining pods must be done by running offline from inside the container and deleting the pod manually.

The same impact probably exists on all the specs from custom resources inherited by the pods (I tested for instance modifying the CPU limit, again only the first pod was updated).

For now, we patched the operator by commenting the [first call to checkAndUpdatePodRevision](https://github.com/splunk/splunk-operator/pull/193/files#diff-28693ad8a99405feca6ef7afadb73ea0c728cc225b46becfbf109e784a9cf4f8R198) from method ```UpdateStatefulSetPods``` (case of ```readyReplicas < replicas```), which fixed the problem. But we don't understand the impact of this modification, as we don't understand the initial purpose of the PR. We never observed cases of unnecessary pod recycle on scaling. Could you please describe these scenarios, and look for a way to address them without causing such an impact on change of CRD specs?

**Comment by gaurav-splunk** [comment] 2020-12-21 18:05
Hi @romain-bellanger Thanks for finding the issue. Let me check it at my end and I'll let you know about the findings and fix at my end.
> But we don't understand the impact of this modification, as we don't understand the initial purpose of the PR. We never observed cases of unnecessary pod recycle on scaling.

We observed in our environment that whenever we tried to scale up/down indexer cluster, it recycled the indexer pods since the `controller-revision-hash` has changed and in our code, we were recycling the pods if there is a change in that label. I am not sure how you tried scaling. We tried using `kubectl scale idxc <idxc-name> --replicas=<new replica count>`.

**Comment by gaurav-splunk** [comment] 2020-12-22 03:42
Hi @romain-bellanger , hopefully this [PR](https://github.com/splunk/splunk-operator/pull/214) should fix the issue you are seeing.

**Comment by romain-bellanger** [comment] 2020-12-22 12:57
Hi @gaurav-splunk, thanks a lot for checking this so quickly!
We mostly experimented auto-scaling, which doesn't modify the ```controller-revision-hash```. Then we are generally using Openshift templates to describe our custom resources, the number of replicas being a parameter of the template. But we haven't used this for a while to scale clusters, and I didn't remember about these unexpected recycles. But this operation changes ```controller-revision-hash``` so the impact was most probably there.

**Comment by akondur** [comment] 2022-04-01 19:19
Hi @romain-bellanger , this issue should be fixed via the following [PR](https://github.com/splunk/splunk-operator/pull/244). Could you please check with the latest release?

**Comment by akondur** [comment] 2022-04-14 18:08
Closing as the issue is fixed in develop/latest release.

**Closed by akondur** 2022-04-14 18:08 UTC
