### ISSUE TITLE
Smart Store secret deleted by operator

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-operator#651] opened 2022-01-13 12:35 UTC
When using an external secret when a deployment is deleted the Secret referenced by smart store is also deleted. Operator should not delete objects it does not create

**Comment by pogdin** [comment] 2022-01-13 15:48
Dupe of https://github.com/splunk/splunk-operator/issues/569

**Closed by pogdin** 2022-01-13 15:48 UTC
