### ISSUE TITLE
Smartstore: pod roles - regional sts endpoint

### ISSUE THREAD

**Issue by dnavaraWH** [splunk/splunk-operator#1325] opened 2024-04-25 14:51 UTC
### Please select the type of request

Enhancement

### Tell us more

**Describe the request**

I am trying to authenticate to SmartStore using IAM role ( pod roles) instead of IAM USER, however as our cluster is in eu-west-1 we can/want to only use sts.eu-west-1.amazonaws.com endpoint. 

It looks like default behaviour is however sts.amazonaws.com, and there seems to be no way to change this. 

We are seeing the following error:
 ERROR AwsCredentials - Failed to execute runSync() for transaction with uri=https://sts.amazonaws.com/ http_code=502
 

**Expected behavior**
I want to be able to set regional sts just like it's done in Splunk add on for AWS

**Splunk setup on K8S**
SOK 2.4.0
Splunk 9.1.2

**Reproduction/Testing steps**
Create cluster in eu-west-1 region and don't allow it to talk to us-east-1 via web proxy

**K8s environment**
K8s v1.28.5-eks-5e0fdde. 
SOK 2.4.0
Splunk 9.1.2

**Proposed changes(optional)**
Allow for regional sts endpoints

**Comment by nfilip21** [comment] 2024-05-17 14:48
Same problem here. 

ERROR AwsCredentials [2434655 cachemanagerUploadExecutorWorker-95] - Failed to execute runSync() for transaction with uri=https://sts.amazonaws.com/ http_code=400
ERROR S3Client [2130967 cachemanagerUploadExecutorWorker-54] - command=put transactionId=0x7f79069d2000 rTxnId=0x7f790681cb00 status=completed success=N uri=xxxxxxxxxxxxxxxxxxxx statusCode=400 statusDescription="Bad Request" payload="<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>....</Token-0><RequestId>xxxxxxxxxxxxxxxxxxx</RequestId><Host"

Our cluster is in eu-central-1.

That means that is only posible to authenticate SmartStore S3 Client using IAM role in the us-east-1 region ?

**Comment by vivekr-splunk** [comment] 2024-10-22 15:25
@dnavaraWH this will be fixed in upcoming release of splunk enterprise planned for mid November

**Comment by akondur** [comment] 2024-11-13 20:38
Hi @dnavaraWH , the fix for AWS IRSA JWT token expiring has been fixed in splunk [9.3.2](https://hub.docker.com/layers/splunk/splunk/9.3.2/images/sha256-e1b8257e12d0e966ce8ba296f1b2be8bd9cbc66e8692d9439f9788db2619851e?context=explore). Please try it and let us know if you are running into further issues.

**Comment by akondur** [comment] 2024-12-10 23:27
Closing this issue as its fixed in 9.3.2. @dnavaraWH Please re-open it if the issue is still pending.

**Closed by akondur** 2024-12-10 23:27 UTC
Labels: smartstore, to-close, 2.7
