### ISSUE TITLE
CrashLoopBackOff of Splunk Operator after upgrade to 2.1.1

### ISSUE THREAD

**Issue by markusspitzli** [splunk/splunk-operator#1009] opened 2022-12-16 08:14 UTC
### Please select the type of request

Bug

### Tell us more

**Describe the request**
The Splunk Operator has been upgraded from 2.1.0 to 2.1.1. Since then the Operator keeps crashing. The Pod has the State CrashLoopBackOff. 

In the logfiles of the operator I see that the crash must somehow be related to updateing the CR STatus

```
2022-12-16T07:44:03.632038149Z INFO updateCRStatus Cache is reflecting the latest CR {"controller": "standalone", "controllerGroup": "enterprise.splunk.com", "controllerKind": "Standalone", "Standalone": {"name":"mycompany-prod","namespace":"mycompany-prod"}, "namespace": "mycompany-prod", "name": "mycompany-prod", "reconcileID": "aa4de5fa-607f-46a5-8f3a-d5917956da72", "original cr version": "186476862", "updated CR version": "186476862"}
34
2022-12-16T07:44:03.63207698Z INFO Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference {"controller": "standalone", "controllerGroup": "enterprise.splunk.com", "controllerKind": "Standalone", "Standalone": {"name":"mycompany-prod","namespace":"mycompany-prod"}, "namespace": "mycompany-prod", "name": "mycompany-prod", "reconcileID": "aa4de5fa-607f-46a5-8f3a-d5917956da72"}
33
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
32
panic: runtime error: invalid memory address or nil pointer dereference
31
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16f1c61]
30
29
goroutine 801 [running]:
28
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
27
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
26
panic({0x1927500, 0x2c5e6a0})
25
/usr/local/go/src/runtime/panic.go:884 +0x212
24
github.com/splunk/splunk-operator/pkg/splunk/enterprise.(*AppInstallPipeline).addWorkersToPipelinePhase(0xc000920540, {0x1f51998?, 0xc0000264b0?}, {0x0, 0x0}, {0xc000c6e838, 0x1, 0xa?})
23
/workspace/pkg/splunk/enterprise/afwscheduler.go:216 +0x4e1
22
github.com/splunk/splunk-operator/pkg/splunk/enterprise.(*AppInstallPipeline).createAndAddPipelineWorker(0x1f52c80?, {0x1f51998, 0xc0000264b0}, {0x0, 0x0}, 0xc0001e8000, {0xc00058dfda, 0x5}, {0xc000a1ab40, 0x21}, ...)
21
/workspace/pkg/splunk/enterprise/afwscheduler.go:68 +0x69c
20
github.com/splunk/splunk-operator/pkg/splunk/enterprise.afwSchedulerEntry({0x1f51998?, 0xc0000264b0}, {0x7fae1debf950?, 0xc00061b4a0}, {0x1f66db8, 0xc000db4a80}, 0xc000db5348, 0xc000db5218)
19
/workspace/pkg/splunk/enterprise/afwscheduler.go:1813 +0xb11
18
github.com/splunk/splunk-operator/pkg/splunk/enterprise.handleAppFrameworkActivity({0x1f51998, 0xc0000264b0}, {0x7fae1debf950, 0xc00061b4a0}, {0x1f66db8?, 0xc000db4a80?}, 0xc000db5348, 0x7fae1debf950?)
17
/workspace/pkg/splunk/enterprise/util.go:1973 +0x345
16
github.com/splunk/splunk-operator/pkg/splunk/enterprise.ApplyStandalone({0x1f51998, 0xc0000264b0}, {0x7fae1debf950?, 0xc00061b4a0}, 0xc000db4a80)
15
/workspace/pkg/splunk/enterprise/standalone.go:230 +0x1a85
14
github.com/splunk/splunk-operator/controllers.glob..func8({0x1f51998, 0xc0000264b0}, {0x1f58c78?, 0xc00061b4a0}, 0x5?)
13
/workspace/controllers/standalone_controller.go:119 +0x58
12
github.com/splunk/splunk-operator/controllers.(*StandaloneReconciler).Reconcile(0xc000642de0, {0x1f51998, 0xc0000264b0}, {{{0xc0008a14f0, 0xd}, {0xc0008a14e0, 0xd}}})
11
/workspace/controllers/standalone_controller.go:109 +0x55b
10
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1f518f0?, {0x1f51998?, 0xc0000264b0?}, {{{0xc0008a14f0?, 0x1a86ac0?}, {0xc0008a14e0?, 0xc000c2add0?}}})
9
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000697a40, {0x1f518f0, 0xc000651240}, {0x19933a0?, 0xc00001c360?})
7
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000697a40, {0x1f518f0, 0xc000651240})
5
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
3
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
2
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
1
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
```

**Expected behavior**
No Crash at all

**Splunk setup on K8S**
- 6 node Kubernetes Cluster: v1.22.12+vmware.1
- Namespaced Installation
- Just a Standalone Instance

** kubectl describe pod splunk-operator ***
```
Name:         splunk-operator-controller-manager-6954597876-ngd59
Namespace:    mycompany-prod
Priority:     0
Node:         8b291e77-dcca-42ad-87e3-a9f0dda94d28/11.0.78.10
Start Time:   Fri, 16 Dec 2022 09:05:13 +0100
Labels:       control-plane=controller-manager
              name=splunk-operator
              pod-template-hash=6954597876
Annotations:  kubectl.kubernetes.io/default-container: manager
              kubectl.kubernetes.io/default-logs-container: manager
              kubernetes.io/psp: splunk-operator-controller-manager
Status:       Running
IP:           11.32.110.5
IPs:
  IP:           11.32.110.5
Controlled By:  ReplicaSet/splunk-operator-controller-manager-6954597876
Containers:
  kube-rbac-proxy:
    Container ID:  docker://c0c6b647c8a9d8118a35c757a8a6d752f658f6f2bc4ae7f30e4d2d0b61d7d185
    Image:         gcr-remote.artifactory.mycompany.com/kubebuilder/kube-rbac-proxy:v0.13.0
    Image ID:      docker-pullable://gcr-remote.artifactory.mycompany.com/kubebuilder/kube-rbac-proxy@sha256:d99a8d144816b951a67648c12c0b988936ccd25cf3754f3cd85ab8c01592248f
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=0
    State:          Running
      Started:      Fri, 16 Dec 2022 09:05:21 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:        5m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vmxdv (ro)
  manager:
    Container ID:  docker://a05ab093cd3729d6f51927602825cf8df80701c401a6c691b6db05c349cac2e3
    Image:         remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1
    Image ID:      docker-pullable://remote-docker.artifactory.mycompany.com/splunk/splunk-operator@sha256:c952e7fc25815bec35282a829f50c9fd52ac9c43f5586163f1cad834d1c779d4
    Port:          <none>
    Host Port:     <none>
    Command:
      /manager
    Args:
      --leader-elect
      --pprof
    State:          Running
      Started:      Fri, 16 Dec 2022 09:11:49 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Dec 2022 09:10:02 +0100
      Finished:     Fri, 16 Dec 2022 09:10:20 +0100
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     1
      memory:  2000Mi
    Requests:
      cpu:      1
      memory:   2000Mi
    Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      WATCH_NAMESPACE:                  mycompany-prod (v1:metadata.namespace)
      RELATED_IMAGE_SPLUNK_ENTERPRISE:  remote-docker.artifactory.mycompany.com/splunk/splunk:9.0.2
      OPERATOR_NAME:                    splunk-operator
      POD_NAME:                         splunk-operator-controller-manager-6954597876-ngd59 (v1:metadata.name)
    Mounts:
      /opt/splunk/appframework/ from app-staging (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vmxdv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  splunk-operator-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      splunk-operator-config
    Optional:  false
  app-staging:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  splunk-operator-app-download
    ReadOnly:   false
  kube-api-access-vmxdv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   Scheduled               6m37s                 default-scheduler        Successfully assigned mycompany-prod/splunk-operator-controller-manager-6954597876-ngd59 to 8b291e77-dcca-42ad-87e3-a9f0dda94d28
  Normal   SuccessfulAttachVolume  6m36s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-3db2e140-9f40-40c7-a417-62a46a777588"
  Normal   Pulled                  6m30s                 kubelet                  Container image "gcr-remote.artifactory.mycompany.com/kubebuilder/kube-rbac-proxy:v0.13.0" already present on machine
  Normal   Created                 6m30s                 kubelet                  Created container kube-rbac-proxy
  Normal   Started                 6m30s                 kubelet                  Started container kube-rbac-proxy
  Normal   Pulled                  6m30s                 kubelet                  Successfully pulled image "remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1" in 250.468517ms
  Normal   Pulled                  6m9s                  kubelet                  Successfully pulled image "remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1" in 238.464965ms
  Normal   Pulled                  3m51s                 kubelet                  Successfully pulled image "remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1" in 240.711456ms
  Normal   Pulling                 3m2s (x4 over 6m30s)  kubelet                  Pulling image "remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1"
  Normal   Created                 3m2s (x4 over 6m30s)  kubelet                  Created container manager
  Normal   Pulled                  3m2s                  kubelet                  Successfully pulled image "remote-docker.artifactory.mycompany.com/splunk/splunk-operator:2.1.1" in 228.054507ms
  Normal   Started                 3m1s (x4 over 6m30s)  kubelet                  Started container manager
  Warning  BackOff                 82s (x12 over 4m1s)   kubelet                  Back-off restarting failed container

```

**Comment by vivekr-splunk** [comment] 2022-12-16 18:03
Hello @markusspitzli , I tried to reproduce the issue with 2.1.1 operator with standalone instance. i am unable to reproduce the problem
```
> kubectl apply -f https://github.com/splunk/splunk-operator/releases/download/2.1.1/splunk-operator-namespace.yaml -n splunk-operator --server-side --force-conflicts
> cat config/examples/standalone/default.yaml 
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: test
spec: 
  extraEnv: 
    - name: DEBUG
      value: "true"
    - name: ANSIBLE_EXTRA_FLAGS
      value: "-vvv"
> kubectl apply -f config/examples/standalone/default.yaml -n splunk-operator
>  kubectl get pods -n splunk-operator
```
splunk-test-standalone-0                              1/1     Running             0          71s
```

**Comment by vivekr-splunk** [comment] 2022-12-16 18:05
@markusspitzli  please share your standalone instance CR , we can try to reproduce the issue

**Comment by markusspitzli** [comment] 2022-12-20 07:23
@vivekr-splunk is it this whatyou are looking for?

```
$ k get standalone mycompany-prod
Name:         mycompany-prod
Namespace:    mycompany-prod
Labels:       app.kubernetes.io/instance=mycompany-prod
Annotations:  argocd.argoproj.io/sync-wave: 3
API Version:  enterprise.splunk.com/v4
Kind:         Standalone
Metadata:
  Creation Timestamp:  2022-07-18T16:07:48Z
  Generation:          7
  Managed Fields:
    API Version:  enterprise.splunk.com/v3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:appContext:
          .:
          f:appRepo:
            .:
            f:appSources:
            f:appsRepoPollIntervalSeconds:
            f:defaults:
              .:
              f:scope:
              f:volumeName:
          f:appSrcDeployStatus:
            .:
            f:local:
          f:appsRepoStatusPollIntervalSeconds:
        f:replicas:
        f:resourceRevMap:
        f:selector:
        f:smartstore:
          .:
          f:cacheManager:
          f:defaults:
    Manager:      manager
    Operation:    Update
    Time:         2022-07-18T16:12:48Z
    API Version:  enterprise.splunk.com/v3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:argocd.argoproj.io/sync-wave:
        f:labels:
      f:spec:
        .:
        f:appRepo:
          .:
          f:appSources:
          f:appsRepoPollIntervalSeconds:
          f:defaults:
            .:
            f:scope:
            f:volumeName:
        f:defaults:
        f:defaultsUrl:
        f:etcVolumeStorageConfig:
          .:
          f:ephemeralStorage:
          f:storageCapacity:
          f:storageClassName:
        f:extraEnv:
        f:resources:
          .:
          f:limits:
            .:
            f:cpu:
            f:memory:
          f:requests:
            .:
            f:cpu:
            f:memory:
        f:varVolumeStorageConfig:
          .:
          f:ephemeralStorage:
          f:storageCapacity:
          f:storageClassName:
    Manager:      argocd-application-controller
    Operation:    Update
    Time:         2022-10-20T13:40:56Z
    API Version:  enterprise.splunk.com/v3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          f:app.kubernetes.io/instance:
    Manager:      argocd-controller
    Operation:    Update
    Time:         2022-11-14T13:24:53Z
    API Version:  enterprise.splunk.com/v4
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:appContext:
          f:appRepo:
            f:volumes:
          f:appSrcDeployStatus:
            f:local:
              f:appDeploymentInfo:
          f:appsStatusMaxConcurrentAppDownloads:
          f:bundlePushStatus:
          f:isDeploymentInProgress:
          f:lastAppInfoCheckTime:
          f:version:
        f:phase:
        f:readyReplicas:
        f:telAppInstalled:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-12-16T07:31:49Z
  Resource Version:  186491722
  UID:               c70a7ceb-768e-4a6e-bb5c-30f88841a492
Spec:
  App Repo:
    App Install Period Seconds:  90
    App Sources:
      Location:                       mycompany-prod/Standalone/local/
      Name:                           local
    Apps Repo Poll Interval Seconds:  300
    Defaults:
      Scope:              local
      Volume Name:        volume_app_repo
    Install Max Retries:  2
    Volumes:
      Endpoint:      https://s3endpoint.mycompany.com
      Name:          volume_app_repo
      Path:          apps/
      Provider:      minio
      Secret Ref:    s3-secret-apps
      Storage Type:  s3
  Defaults:          splunk:
  conf:
    - key: alert_actions
      value:
        directory: /opt/splunk/etc/system/local
        content:
          email:
            hostname: https://45370800.prod.datainsights.mycompany.com
    - key: authentication
      value:
        directory: /opt/splunk/etc/system/local
        content:
          saml:
            entityId: splunk-mycompany-prod
            fqdn: https://45370800.prod.datainsights.mycompany.com

    - key: inputs
      value:
        directory: /opt/splunk/etc/system/local
        content:
          "splunktcp-ssl://9998":
            route: "has_key:_utf8:parsingQueue;has_key:_linebreaker:parsingQueue;absent_key:_utf8:parsingQueue;absent_key:_linebreaker:parsingQueue;"
  Defaults URL:  /mnt/license-master/default.yaml
  Etc Volume Storage Config:
    Ephemeral Storage:   false
    Storage Capacity:    2Gi
    Storage Class Name:  fast
  Extra Env:
    Name:   TZ
    Value:  Europe/Zurich
  Resources:
    Limits:
      Cpu:     8
      Memory:  4Gi
    Requests:
      Cpu:     100m
      Memory:  4Gi
  Var Volume Storage Config:
    Ephemeral Storage:   false
    Storage Capacity:    20Gi
    Storage Class Name:  fast
  Volumes:
    Name:  license-master
    Secret:
      Secret Name:  splunk-license-master
Status:
  App Context:
    App Repo:
      App Install Period Seconds:  90
      App Sources:
        Location:                       mycompany-prod/Standalone/local/
        Name:                           local
      Apps Repo Poll Interval Seconds:  300
      Defaults:
        Scope:              local
        Volume Name:        volume_app_repo
      Install Max Retries:  2
      Volumes:
        Endpoint:      https://s3endpoint.mycompany.com
        Name:          volume_app_repo
        Path:          apps/
        Provider:      minio
        Region:
        Secret Ref:    s3-secret-apps
        Storage Type:  s3
    App Src Deploy Status:
      Local:
        App Deployment Info:
          App Name:       k8s_internal_logs_indexers.tgz
          Deploy Status:  3
          Is Update:      false
          Object Hash:    ee803c42cfc33139533af904475857ef
          Phase Info:
          Repo State:     2
          App Name:       k8s_keycloak.tgz
          Deploy Status:  3
          Is Update:      false
          Object Hash:    ad0d9a5d880607b3249846db5e024ed5
          Phase Info:
          Repo State:     2
          App Name:       ia-dis-defaults-all.tgz
          Deploy Status:  3
          Is Update:      false
          Object Hash:    46f49e31e83cff8467e2fa1096e99c15
          Phase Info:
            Phase:        install
            Status:       303
          Repo State:     1
          App Name:       ia-dis-defaults-scs.tgz
          Deploy Status:  3
          Is Update:      false
          Object Hash:    342c349c1312dcaf2cd11e3b19833e5a
          Phase Info:
            Phase:        install
            Status:       303
          Repo State:     1
          App Name:       ia-dis-defaults-scs-prod.tgz
          Deploy Status:  3
          Is Update:      false
          Object Hash:    7123d1af6bc6f13ca9d93da7dbff276b
          Phase Info:
            Phase:                             install
            Status:                            303
          Repo State:                          1
    Apps Repo Status Poll Interval Seconds:    300
    Apps Status Max Concurrent App Downloads:  5
    Bundle Push Status:
    Is Deployment In Progress:  true
    Last App Info Check Time:   1671175909
    Version:                    1
  Phase:                        Ready
  Ready Replicas:               1
  Replicas:                     1
  Resource Rev Map:
  Selector:  app.kubernetes.io/instance=splunk-mycompany-prod-standalone
  Smartstore:
    Cache Manager:
    Defaults:
  Tel App Installed:  false
Events:               <none>
```

and this one

```
$ k get standalone mycompany-prod -o yaml
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"enterprise.splunk.com/v3","kind":"Standalone","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"3"},"labels":{"app.kubernetes.io/instance":"mycompany-prod"},"name":"mycompany-prod","namespace":"mycompany-prod"},"spec":{"appRepo":{"appSources":[{"location":"mycompany-prod/Standalone/local/","name":"local"}],"appsRepoPollIntervalSeconds":300,"defaults":{"scope":"local","volumeName":"volume_app_repo"},"volumes":[{"endpoint":"https://s3endpoint.mycompany.com","name":"volume_app_repo","path":"apps/","provider":"minio","secretRef":"s3-secret-apps","storageType":"s3"}]},"defaults":"splunk:\n  conf:\n    - key: alert_actions\n      value:\n        directory: /opt/splunk/etc/system/local\n        content:\n          email:\n            hostname: https://45370800.prod.datainsights.mycompany.com\n    - key: authentication\n      value:\n        directory: /opt/splunk/etc/system/local\n        content:\n          saml:\n            entityId: splunk-mycompany-prod\n            fqdn: https://45370800.prod.datainsights.mycompany.com\n    \n    - key: inputs\n      value:\n        directory: /opt/splunk/etc/system/local\n        content:\n          \"splunktcp-ssl://9998\":\n            route: \"has_key:_utf8:parsingQueue;has_key:_linebreaker:parsingQueue;absent_key:_utf8:parsingQueue;absent_key:_linebreaker:parsingQueue;\"","defaultsUrl":"/mnt/license-master/default.yaml","etcVolumeStorageConfig":{"ephemeralStorage":false,"storageCapacity":"2Gi","storageClassName":"fast"},"extraEnv":[{"name":"TZ","value":"Europe/Zurich"}],"resources":{"limits":{"cpu":"8","memory":"4Gi"},"requests":{"cpu":"100m","memory":"4Gi"}},"varVolumeStorageConfig":{"ephemeralStorage":false,"storageCapacity":"20Gi","storageClassName":"fast"},"volumes":[{"name":"license-master","secret":{"secretName":"splunk-license-master"}}]}}
  creationTimestamp: "2022-07-18T16:07:48Z"
  generation: 7
  labels:
    app.kubernetes.io/instance: mycompany-prod
  managedFields:
  - apiVersion: enterprise.splunk.com/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:appContext:
          .: {}
          f:appRepo:
            .: {}
            f:appSources: {}
            f:appsRepoPollIntervalSeconds: {}
            f:defaults:
              .: {}
              f:scope: {}
              f:volumeName: {}
          f:appSrcDeployStatus:
            .: {}
            f:local: {}
          f:appsRepoStatusPollIntervalSeconds: {}
        f:replicas: {}
        f:resourceRevMap: {}
        f:selector: {}
        f:smartstore:
          .: {}
          f:cacheManager: {}
          f:defaults: {}
    manager: manager
    operation: Update
    time: "2022-07-18T16:12:48Z"
  - apiVersion: enterprise.splunk.com/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:argocd.argoproj.io/sync-wave: {}
        f:labels: {}
      f:spec:
        .: {}
        f:appRepo:
          .: {}
          f:appSources: {}
          f:appsRepoPollIntervalSeconds: {}
          f:defaults:
            .: {}
            f:scope: {}
            f:volumeName: {}
        f:defaults: {}
        f:defaultsUrl: {}
        f:etcVolumeStorageConfig:
          .: {}
          f:ephemeralStorage: {}
          f:storageCapacity: {}
          f:storageClassName: {}
        f:extraEnv: {}
        f:resources:
          .: {}
          f:limits:
            .: {}
            f:cpu: {}
            f:memory: {}
          f:requests:
            .: {}
            f:cpu: {}
            f:memory: {}
        f:varVolumeStorageConfig:
          .: {}
          f:ephemeralStorage: {}
          f:storageCapacity: {}
          f:storageClassName: {}
    manager: argocd-application-controller
    operation: Update
    time: "2022-10-20T13:40:56Z"
  - apiVersion: enterprise.splunk.com/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app.kubernetes.io/instance: {}
    manager: argocd-controller
    operation: Update
    time: "2022-11-14T13:24:53Z"
  - apiVersion: enterprise.splunk.com/v4
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:appContext:
          f:appRepo:
            f:volumes: {}
          f:appSrcDeployStatus:
            f:local:
              f:appDeploymentInfo: {}
          f:appsStatusMaxConcurrentAppDownloads: {}
          f:bundlePushStatus: {}
          f:isDeploymentInProgress: {}
          f:lastAppInfoCheckTime: {}
          f:version: {}
        f:phase: {}
        f:readyReplicas: {}
        f:telAppInstalled: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2022-12-16T07:31:49Z"
  name: mycompany-prod
  namespace: mycompany-prod
  resourceVersion: "186491722"
  uid: c70a7ceb-768e-4a6e-bb5c-30f88841a492
spec:
  appRepo:
    appInstallPeriodSeconds: 90
    appSources:
    - location: mycompany-prod/Standalone/local/
      name: local
    appsRepoPollIntervalSeconds: 300
    defaults:
      scope: local
      volumeName: volume_app_repo
    installMaxRetries: 2
    volumes:
    - endpoint: https://s3endpoint.mycompany.com
      name: volume_app_repo
      path: apps/
      provider: minio
      secretRef: s3-secret-apps
      storageType: s3
  defaults: "splunk:\n  conf:\n    - key: alert_actions\n      value:\n        directory:
    /opt/splunk/etc/system/local\n        content:\n          email:\n            hostname:
    https://45370800.prod.datainsights.mycompany.com\n    - key: authentication\n      value:\n
    \       directory: /opt/splunk/etc/system/local\n        content:\n          saml:\n
    \           entityId: splunk-mycompany-prod\n            fqdn: https://45370800.prod.datainsights.mycompany.com\n
    \   \n    - key: inputs\n      value:\n        directory: /opt/splunk/etc/system/local\n
    \       content:\n          \"splunktcp-ssl://9998\":\n            route: \"has_key:_utf8:parsingQueue;has_key:_linebreaker:parsingQueue;absent_key:_utf8:parsingQueue;absent_key:_linebreaker:parsingQueue;\""
  defaultsUrl: /mnt/license-master/default.yaml
  etcVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 2Gi
    storageClassName: fast
  extraEnv:
  - name: TZ
    value: Europe/Zurich
  resources:
    limits:
      cpu: "8"
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 4Gi
  varVolumeStorageConfig:
    ephemeralStorage: false
    storageCapacity: 20Gi
    storageClassName: fast
  volumes:
  - name: license-master
    secret:
      secretName: splunk-license-master
status:
  appContext:
    appRepo:
      appInstallPeriodSeconds: 90
      appSources:
      - location: mycompany-prod/Standalone/local/
        name: local
      appsRepoPollIntervalSeconds: 300
      defaults:
        scope: local
        volumeName: volume_app_repo
      installMaxRetries: 2
      volumes:
      - endpoint: https://s3endpoint.mycompany.com
        name: volume_app_repo
        path: apps/
        provider: minio
        region: ""
        secretRef: s3-secret-apps
        storageType: s3
    appSrcDeployStatus:
      local:
        appDeploymentInfo:
        - appName: k8s_internal_logs_indexers.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: ee803c42cfc33139533af904475857ef
          phaseInfo: {}
          repoState: 2
        - appName: k8s_keycloak.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: ad0d9a5d880607b3249846db5e024ed5
          phaseInfo: {}
          repoState: 2
        - appName: ia-dis-defaults-all.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: 46f49e31e83cff8467e2fa1096e99c15
          phaseInfo:
            phase: install
            status: 303
          repoState: 1
        - appName: ia-dis-defaults-scs.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: 342c349c1312dcaf2cd11e3b19833e5a
          phaseInfo:
            phase: install
            status: 303
          repoState: 1
        - appName: ia-dis-defaults-scs-prod.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: 7123d1af6bc6f13ca9d93da7dbff276b
          phaseInfo:
            phase: install
            status: 303
          repoState: 1
    appsRepoStatusPollIntervalSeconds: 300
    appsStatusMaxConcurrentAppDownloads: 5
    bundlePushStatus: {}
    isDeploymentInProgress: true
    lastAppInfoCheckTime: 1671175909
    version: 1
  phase: Ready
  readyReplicas: 1
  replicas: 1
  resourceRevMap: {}
  selector: app.kubernetes.io/instance=splunk-mycompany-prod-standalone
  smartstore:
    cacheManager: {}
    defaults: {}
  telAppInstalled: false

```

**Comment by iaroslav-nakonechnikov** [comment] 2023-01-09 15:44
@markusspitzli i see that you are using saml configuration in splunk. 
may i ask for more details about it?

**Comment by markusspitzli** [comment] 2023-01-12 14:07
@iaroslav-nakonechnikov what exactly do you need to know?

**Comment by gaurav-splunk** [comment] 2023-01-19 01:24
@markusspitzli 
Based on your standalone CR status - 
```
appSrcDeployStatus:
      local:
        appDeploymentInfo:
        - appName: k8s_internal_logs_indexers.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: ee803c42cfc33139533af904475857ef
          phaseInfo: {}
          repoState: 2
        - appName: k8s_keycloak.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: ad0d9a5d880607b3249846db5e024ed5
          phaseInfo: {}
          repoState: 2
        - appName: ia-dis-defaults-all.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: 46f49e31e83cff8467e2fa1096e99c15
          phaseInfo:
            phase: install
            status: 303
          repoState: 1
        - appName: ia-dis-defaults-scs.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: 342c349c1312dcaf2cd11e3b19833e5a
          phaseInfo:
            phase: install
            status: 303
          repoState: 1
        - appName: ia-dis-defaults-scs-prod.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: 7123d1af6bc6f13ca9d93da7dbff276b
          phaseInfo:
            phase: install
            status: 303
          repoState: 1
```

It looks like you deleted a couple of apps i.e. `k8s_keycloak.tgz` and `k8s_internal_logs_indexers.tgz` as their repo state is `2` which means the apps were deleted from remote store. Is that correct? Also, can you tell me the exact steps you did which led to this situation? I mean is it like, you installed few apps, deleted few apps, and then installed few more apps and then upgraded or something else? I am just trying to understand the sequence of events wrt app installs/deletion that happened before the upgrade.

**Comment by markusspitzli** [comment] 2023-01-20 07:57
hi @gaurav-splunk 

Yes, we need to delete apps sometimes. We wrote our own job that deletes the app on the S3 and also changes the app-list configmap. 
I deleted the "splunk-my-company-standalone-app-list" but it doesn't seem to have any effect. Do you still use this app-list with the SOK 2.1.1? where do you store the information which app has been deployed?

**Comment by markusspitzli** [comment] 2023-01-20 13:26
hi @gaurav-splunk 
I was able to fix the issue by deleting the standalone CR. After the deletion the splunk operator started successfully and upgraded the Standalone instance to 9.0.2
But still. It's not great that a difference between the available apps on S3 and the definititon in the standalone CR breaks the startup of the Splunk operator

**Comment by akondur** [comment] 2023-02-06 17:57
Hey @markusspitzli , after investigating the issue it seems like the phaseInfo being empty for these two apps:

```
        - appName: k8s_internal_logs_indexers.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: ee803c42cfc33139533af904475857ef
          phaseInfo: {}
          repoState: 2
        - appName: k8s_keycloak.tgz
          deployStatus: 3
          isUpdate: false
          objectHash: ad0d9a5d880607b3249846db5e024ed5
          phaseInfo: {}
          repoState: 2
```

is causing the crash on the operator. I tried multiple combinations of creation, modification, deletion of app sources in CR spec and apps on S3 bucket and wasn't able to reproduce the issue. To prevent the crash, we will put in a preventive fix soon which I'll update here.

Meanwhile, if you have exact steps on how to reproduce the issue and are able to reproduce the issue consistently on your end please mention those here so that we can take a further look.

**Comment by akondur** [comment] 2023-02-09 00:08
Hi @markusspitzli , here is the preventive fix [PR](https://github.com/splunk/splunk-operator/pull/1053).

**Comment by akondur** [comment] 2023-04-14 21:42
Closing with [2.2.1 release](https://github.com/splunk/splunk-operator/releases/tag/2.2.1)

**Closed by akondur** 2023-04-14 21:42 UTC
Labels: closewithnextrelease, 2.1.1, upgrade
