### ISSUE TITLE
Cluster Master needs separate storage class than Indexers

### ISSUE THREAD

**Issue by crawdaddy18** [splunk/splunk-operator#110] opened 2020-08-26 15:27 UTC
I need to be able to overwrite or otherwise assign a different storage class to the Cluster Master.  Currently, the CM inherits the settings used for the Indexers.

In my install, I am using OpenEBS for the indexers to take advantage of local storage, however, I need to persist data for the CM and OpenEBS is not the right choice for that if the node where CM is running fails.

Please LMK if this setting can be overwritten in a manifest or if a change can be made to the SOK and the operator recompiled.

#A380

**Comment by gaurav-splunk** [comment] 2020-08-26 17:21
Hi @crawdaddy18, this is definitely possible. We recently merged a [PR](https://github.com/splunk/splunk-operator/pull/99), where you can have a separate CR for CM other than indexers. In CR for CM, you have to specify `replicas:0` and in the CR for indexers, you have to refer to CM using section `indexerClusterRef` which points to the name you give in the CR for CM. This way you can have a configuration/storage class for CM which is different from indexers.
A simple example would look something like this - 
CR for ClusterMaster -
```apiVersion: enterprise.splunk.com/v1alpha3
kind: IndexerCluster
metadata:
  name: cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 0
```
And a CR for indexers would look something like this - 
```apiVersion: enterprise.splunk.com/v1alpha3
kind: IndexerCluster
metadata:
  name: idxc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 2
  indexerClusterRef:
    name: cm
```

That being said, we are working on a story where we will have a separate CRD for ClusterMaster to make it more explicit and then we don't have to use `replicas:0` as method to denote spec for CM.

**Comment by crawdaddy18** [comment] 2020-08-26 19:21
Thank you @gaurav-splunk is this the output you'd expect? (the second container is an ISTIO sidecar)
```
splunk-cm-cluster-master-0        2/2     Running   0          2m33s
splunk-cm-indexer-0               2/2     Running   0          2m33s
splunk-idxc-cluster-master-0      2/2     Running   0          2m22s
splunk-idxc-indexer-0             2/2     Running   0          2m22s
splunk-idxc-indexer-1             2/2     Running   0          2m12s
```
manifest:
```
apiVersion: enterprise.splunk.com/v1alpha2
kind: IndexerCluster
metadata:
  name: cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 0
  spec:
  storageClassName: "mapr-nfscsi"
---
apiVersion: enterprise.splunk.com/v1alpha2
kind: IndexerCluster
metadata:
  name: idxc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
spec:
  storageClassName: "openebs-hostpath"
  replicas: 2
  indexerClusterRef:
    name: cm
```

How does Splunk know to use the CM using "mapr-nfscsi" but the indexers for "openebs-hostpath"?

**Comment by crawdaddy18** [comment] 2020-08-26 19:25
Oh wait, I think i get it.  You point your indexers to the "cm" with indexerClusterRef.

So, essentially, 
```
splunk-cm-indexer-0               2/2     Running   0          2m33s
splunk-idxc-cluster-master-0      2/2     Running   0          2m22s
```

Are not doing anything?

**Comment by gaurav-splunk** [comment] 2020-08-26 19:36
Hi @crawdaddy18, I think you are not using the latest splunk-operator code from develop. As I mentioned this [PR](https://github.com/splunk/splunk-operator/pull/99) was merged recently to develop branch.
If you are using the splunk-operator version which does not have that change, then if you pass `replicas:0` to the CR, it will default to `replicas:1` and will go ahead and create an indexer cluster with cm and 1 indexer.
But, if you had the splunk-operator version which has that change, then it will only create a CM(if a CR has `replicas:0`) and not the indexer part of it. So, when you create another CR with non-zero replicas **AND** indexerClusterRef pointing to the CM you just created( with `replicas:0`), it will create the indexers part of indexer cluster and point to CM. So in a nutshell, you can only use the above approach if you have the splunk-operator version with the recent change.
I hope this makes sense!

**Comment by crawdaddy18** [comment] 2020-08-26 21:26
@gaurav-splunk understood.  Would it be possible to get a recent build that includes PR 99 from the develop branch?  I tried to build earlier, but the "make tidy" command fails when trying to pull some go packages.  I believe the instructions for how to build the SOK need to be updated.  I can open another issue if needed to address the build instructions.

**Comment by gaurav-splunk** [comment] 2020-08-26 21:34
You can pull the latest image from `splunk/splunk-operator:edge` by running 
```docker pull splunk/splunk-operator:edge```
The CI pipeline keeps `edge` tag up to date with develop. (Thanks to @mikedickey for this info!)

**Comment by crawdaddy18** [comment] 2020-08-26 23:05
@gaurav-splunk @mikedickey Thank you, but I'm still running into some issues.  (FWIW--I just did a wget on the tiny.cc url and changed the version from 0.1.0 to edge)

Issue #1 - Splunk Operator is failing
```
splunk-operator-5f896cf567-nmctt   1/2     CrashLoopBackOff   5          3m57s
```
```
Chriss-MacBook-Pro:.kube chriscrawford$ kubectl logs po/splunk-operator-5f896cf567-nmctt
error: a container name must be specified for pod splunk-operator-5f896cf567-nmctt, choose one of: [splunk-operator istio-proxy] or one of the init containers: [istio-init]
Chriss-MacBook-Pro:.kube chriscrawford$ kubectl logs po/splunk-operator-5f896cf567-nmctt -c splunk-container
error: container splunk-container is not valid for pod splunk-operator-5f896cf567-nmctt
Chriss-MacBook-Pro:.kube chriscrawford$ kubectl logs po/splunk-operator-5f896cf567-nmctt -c splunk-operator
{"level":"info","ts":1598482958.5798361,"logger":"cmd","msg":"Splunk Operator for Kubernetes","Version":"0.2.0","SDK.Version":"v0.15.1","Go.Version":"go1.13.6","Go.OS":"linux","Go.Arch":"amd64"}
{"level":"info","ts":1598482958.580193,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1598482959.7449815,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1598482959.745055,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1598482959.7450612,"logger":"cmd","msg":"Creating new manager","namespace":"splunk"}
{"level":"info","ts":1598482960.9003975,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1598482960.9011238,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1598482963.207164,"logger":"cmd","msg":"Could not generate and serve custom resource metrics","error":"discovering resource information failed for LicenseMaster in enterprise.splunk.com/v1alpha3: apiVersion enterprise.splunk.com/v1alpha3 and kind LicenseMaster not found available in Kubernetes cluster"}
{"level":"info","ts":1598482964.3918643,"logger":"metrics","msg":"Metrics Service object updated","Service.Name":"splunk-operator-metrics","Service.Namespace":"splunk"}
{"level":"info","ts":1598482965.5437293,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1598482965.5437725,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1598482965.5437794,"logger":"cmd","msg":"Starting the Manager."}
{"level":"info","ts":1598482965.5441084,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"Standalone","source":"kind source: enterprise.splunk.com/v1alpha3, Kind=Standalone"}
{"level":"info","ts":1598482965.544198,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"IndexerCluster","source":"kind source: enterprise.splunk.com/v1alpha3, Kind=IndexerCluster"}
{"level":"info","ts":1598482965.5443392,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"SearchHeadCluster","source":"kind source: enterprise.splunk.com/v1alpha3, Kind=SearchHeadCluster"}
{"level":"info","ts":1598482965.544373,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"LicenseMaster","source":"kind source: enterprise.splunk.com/v1alpha3, Kind=LicenseMaster"}
{"level":"info","ts":1598482965.5441697,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1598482965.5444574,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"Spark","source":"kind source: enterprise.splunk.com/v1alpha3, Kind=Spark"}
{"level":"error","ts":1598482966.697183,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"Standalone.enterprise.splunk.com","error":"no matches for kind \"Standalone\" in version \"enterprise.splunk.com/v1alpha3\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\tgo/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.go:477"}
{"level":"error","ts":1598482966.6973162,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"Standalone\" in version \"enterprise.splunk.com/v1alpha3\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgo/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tsplunk-operator/cmd/manager/main.go:142\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

Issue #2 
the finalizers in:
```
indexerclusters.enterprise.splunk.com                        2020-08-26T22:59:19Z
licensemasters.enterprise.splunk.com                         2020-08-26T22:59:18Z
```
Will not let me delete the splunk-operator.  I have to manual edit the CRDs and remove the finalizers to get them to shake loose

**Comment by gaurav-splunk** [comment] 2020-08-27 17:32
@crawdaddy18  For issue#1, you have to first install the CRDs or register them to the API server.
If you do `kubectl get crds` and it shows nothing that means you have not applied them. Maybe you can paste or attach your yaml file which you are using to try to deploy the operator?
I have to check about issue#2 or maybe @mikedickey can chime in here?

**Comment by gaurav-splunk** [comment] 2020-08-27 18:26
Ok, I think I got what the issue is. The CRDs in the yaml from the tiny.cc URL is not compatible with the latest splunk-operator image. You need to explicitly deploy the CRDs from the latest develop branch. Here is what you can do - 
1.  You can just grab the section which deploys the splunk-operator from the yaml file you downloaded and copy it in a separate yaml file.
2. Change the image version 0.1.0 to edge.
3. You can clone the latest develop branch in your environment and then do ```kubectl apply -f deploy/crds/``` to deploy the CRDs
4. Now, you can deploy the operator using the yaml file which only has the Deployment section for splunk-operator.
This worked in my environment fine. Let me know if it worked for you too.

**Comment by crawdaddy18** [comment] 2020-08-27 19:01
Thank you @gaurav-splunk it appears to be up and running as expected

```
splunk-cm-cluster-master-0         1/2     Running   0          31s
splunk-idxc-indexer-0              1/2     Running   0          31s
splunk-idxc-indexer-1              1/2     Running   0          31s
```

**Comment by crawdaddy18** [comment] 2020-08-27 19:03
There appears to be no issues with the finalizers when applying CRDs in the order describe here.  Everything tore down cleanly.

**Comment by gaurav-splunk** [comment] 2020-08-27 19:07
Nice!! I am glad that it worked for you :)

**Comment by crawdaddy18** [comment] 2020-09-08 21:17
@gaurav-splunk I have made a lot of progress, but I think there are some issues with how the services are routing.  At this time, I am struggling with sending data via HEC on container port 8088.

I was able to successfully run the following code on splunk container splunk-cm-cluster-master-0:
```
curl -k -L -v "http://localhost:8088/services/collector" \
  -H "Authorization: Splunk 88785717-af3c-4270-a20e-3a665ec0a3af" \
  --header 'Content-Type: application/json' \
  -d '{"event": "hello world","sourcetype": "manual"}'
```
I created a new indexer and a HEC token which takes JSON with no timestamp into this new index.  I also turned off SSL and acknowledgements.

However, I cannot hit this container port from outside the container.  Each time it fails.  I have even tried to just hit it from the K8S Master using the ClusterIP.

I also exec'd into the splunk container splunk-lab-indexer-0, but this code will not run at all.

I'm kind of guessing here, but would you mind looking at using a HEC Token in this configuration?  And if you can get it to work, please post your instructions here?

Thanks in advance

**Comment by crawdaddy18** [comment] 2020-09-08 21:31
@gaurav-splunk I fixed part of it.  I had to modify the service splunk-cm-indexer-service and change "name: indexer" to "name: cluster-master"

```  selector:
    app.kubernetes.io/component: indexer
    app.kubernetes.io/managed-by: splunk-operator
    app.kubernetes.io/name: cluster-master
    app.kubernetes.io/part-of: splunk-cm-indexer
```

**Comment by crawdaddy18** [comment] 2020-09-08 21:36
@gaurav-splunk but here is my current issue.  The message has been received, but it was not added to the new index.  This may just be my lack of knowledge

```
Search peer splunk-lab-indexer-0 has the following message: Received event for unconfigured/disabled/deleted index=ezmeral with source="source::http:splunk" host="host::10.100.204.82:8088" sourcetype="sourcetype::manual". So far received events from 1 missing index(es).
```

**Comment by Caldas** [comment] 2020-09-08 23:32
Cris, look like you didn't setup the index

Em ter, 8 de set de 2020 18:36, Chris C <notifications@github.com> escreveu:

**Comment by crawdaddy18** [comment] 2020-09-10 17:53
@gaurav-splunk @Caldas The index was set up on the Cluster Master, however, it was pointed out later that the Indexers did not know anything about the new index and thus the message.  A splunk guru helped me push the configurations from the Cluster Master to the indexers and it is all working now. I'm not sure I could re-do what they did, but that's the general issue.

Perhaps it would be good to document somewhere how to get it all set up when the Indexers have a different CM?

**Comment by pogdin** [comment] 2020-10-29 17:21
@crawdaddy18 , would you consider this delivered in the beta release with the separation of index cluster members and the cluster master?

**Comment by pogdin** [comment] 2020-12-02 16:08
Delivered in 0.2.0 beta with new cluster master CRD

**Closed by pogdin** 2020-12-02 16:08 UTC
